spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database-v14;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
      firstName: Admin
      lastName: Administrator
    database:
      type: h2
      schema-update: true
    datasource:
      url: jdbc:h2:file:./camunda-h2-database-v14;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: sa
      driver-class-name: org.h2.Driver