spring.datasource.url: jdbc:h2:file:./camunda-h2-database
spring.datasource.username: sa
spring.datasource.password: sa

camunda.bpm.admin-user:
  id: demo
  password: demo
  firstName: Admin
  lastName: Administrator